name: Automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - reopened
      - unlocked
    branches:
      - develop
      - main
      - production
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_REMOVE_LABELS: "automerge,!wip,!work in progress"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
