on:
  push:
    tags:
      - 'v*'
name: Publish to npm registry
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v5
        with:
          cache: 'pnpm'

      - name: Create .npmrc file for github registry
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          @digital-swing:registry=https://npm.pkg.github.com
          always-auth = true
          auto-install-peers=true' > ${{ github.workspace }}/.npmrc

      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --access restricted --no-git-checks

      - name: Create .npmrc file for npm registry
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}
          @digital-swing:registry=https://registry.npmjs.org/
          always-auth = true
          auto-install-peers=true' >> ${{ github.workspace }}/.npmrc

      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --access public --no-git-checks
