on:
  push:
    tags:
      - 'v*'
name: Publish to npm registry
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish
