on:
  push:
    branches:
      - main
      - "!renovate/pin-dependencies"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
  workflow_dispatch:

name: Build & Test
jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Create .npmrc file
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}
          @digital-swing:registry=https://registry.npmjs.org/
          always-auth = true
          auto-install-peers=true' >> ${{ github.workspace }}/.npmrc

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
